// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v4

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsAcServiceUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AC_SERVICE_UNAVAILABLE.String() && e.Code == 500
}

func ErrorAcServiceUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AC_SERVICE_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}

func IsAcWrongPassword(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AC_WRONG_PASSWORD.String() && e.Code == 500
}

func ErrorAcWrongPassword(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_AC_WRONG_PASSWORD.String(), fmt.Sprintf(format, args...))
}
