// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RefreshDeviceReq_PushChannelType int32

const (
	RefreshDeviceReq_fcm RefreshDeviceReq_PushChannelType = 0
)

var RefreshDeviceReq_PushChannelType_name = map[int32]string{
	0: "fcm",
}

var RefreshDeviceReq_PushChannelType_value = map[string]int32{
	"fcm": 0,
}

func (x RefreshDeviceReq_PushChannelType) String() string {
	return proto.EnumName(RefreshDeviceReq_PushChannelType_name, int32(x))
}

func (RefreshDeviceReq_PushChannelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4, 0}
}

type RegisterReq struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LoginResp struct {
	// CustomToken that can be used to login Firebase.
	CustomToken          string   `protobuf:"bytes,1,opt,name=customToken,proto3" json:"customToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetCustomToken() string {
	if m != nil {
		return m.CustomToken
	}
	return ""
}

type GetProfileReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileReq) Reset()         { *m = GetProfileReq{} }
func (m *GetProfileReq) String() string { return proto.CompactTextString(m) }
func (*GetProfileReq) ProtoMessage()    {}
func (*GetProfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *GetProfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileReq.Unmarshal(m, b)
}
func (m *GetProfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileReq.Marshal(b, m, deterministic)
}
func (m *GetProfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileReq.Merge(m, src)
}
func (m *GetProfileReq) XXX_Size() int {
	return xxx_messageInfo_GetProfileReq.Size(m)
}
func (m *GetProfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileReq proto.InternalMessageInfo

func (m *GetProfileReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type Profile struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Nationality          string   `protobuf:"bytes,6,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Profile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Profile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetNationality() string {
	if m != nil {
		return m.Nationality
	}
	return ""
}

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RefreshDeviceReq struct {
	DeviceId             string                           `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	DeviceModel          string                           `protobuf:"bytes,2,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	DeviceName           string                           `protobuf:"bytes,3,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	PushChannel          RefreshDeviceReq_PushChannelType `protobuf:"varint,4,opt,name=pushChannel,proto3,enum=xmux.core.user.v4.RefreshDeviceReq_PushChannelType" json:"pushChannel,omitempty"`
	PushKey              string                           `protobuf:"bytes,5,opt,name=pushKey,proto3" json:"pushKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *RefreshDeviceReq) Reset()         { *m = RefreshDeviceReq{} }
func (m *RefreshDeviceReq) String() string { return proto.CompactTextString(m) }
func (*RefreshDeviceReq) ProtoMessage()    {}
func (*RefreshDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *RefreshDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshDeviceReq.Unmarshal(m, b)
}
func (m *RefreshDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshDeviceReq.Marshal(b, m, deterministic)
}
func (m *RefreshDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshDeviceReq.Merge(m, src)
}
func (m *RefreshDeviceReq) XXX_Size() int {
	return xxx_messageInfo_RefreshDeviceReq.Size(m)
}
func (m *RefreshDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshDeviceReq proto.InternalMessageInfo

func (m *RefreshDeviceReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *RefreshDeviceReq) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *RefreshDeviceReq) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *RefreshDeviceReq) GetPushChannel() RefreshDeviceReq_PushChannelType {
	if m != nil {
		return m.PushChannel
	}
	return RefreshDeviceReq_fcm
}

func (m *RefreshDeviceReq) GetPushKey() string {
	if m != nil {
		return m.PushKey
	}
	return ""
}

type GetDevicesResp struct {
	Devices              []*GetDevicesResp_Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetDevicesResp) Reset()         { *m = GetDevicesResp{} }
func (m *GetDevicesResp) String() string { return proto.CompactTextString(m) }
func (*GetDevicesResp) ProtoMessage()    {}
func (*GetDevicesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *GetDevicesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesResp.Unmarshal(m, b)
}
func (m *GetDevicesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesResp.Marshal(b, m, deterministic)
}
func (m *GetDevicesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesResp.Merge(m, src)
}
func (m *GetDevicesResp) XXX_Size() int {
	return xxx_messageInfo_GetDevicesResp.Size(m)
}
func (m *GetDevicesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesResp proto.InternalMessageInfo

func (m *GetDevicesResp) GetDevices() []*GetDevicesResp_Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type GetDevicesResp_Device struct {
	DeviceId             string               `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	DeviceModel          string               `protobuf:"bytes,2,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	DeviceName           string               `protobuf:"bytes,3,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	LastSeen             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDevicesResp_Device) Reset()         { *m = GetDevicesResp_Device{} }
func (m *GetDevicesResp_Device) String() string { return proto.CompactTextString(m) }
func (*GetDevicesResp_Device) ProtoMessage()    {}
func (*GetDevicesResp_Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5, 0}
}

func (m *GetDevicesResp_Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesResp_Device.Unmarshal(m, b)
}
func (m *GetDevicesResp_Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesResp_Device.Marshal(b, m, deterministic)
}
func (m *GetDevicesResp_Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesResp_Device.Merge(m, src)
}
func (m *GetDevicesResp_Device) XXX_Size() int {
	return xxx_messageInfo_GetDevicesResp_Device.Size(m)
}
func (m *GetDevicesResp_Device) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesResp_Device.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesResp_Device proto.InternalMessageInfo

func (m *GetDevicesResp_Device) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *GetDevicesResp_Device) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *GetDevicesResp_Device) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *GetDevicesResp_Device) GetLastSeen() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeen
	}
	return nil
}

func init() {
	proto.RegisterEnum("xmux.core.user.v4.RefreshDeviceReq_PushChannelType", RefreshDeviceReq_PushChannelType_name, RefreshDeviceReq_PushChannelType_value)
	proto.RegisterType((*RegisterReq)(nil), "xmux.core.user.v4.RegisterReq")
	proto.RegisterType((*LoginResp)(nil), "xmux.core.user.v4.LoginResp")
	proto.RegisterType((*GetProfileReq)(nil), "xmux.core.user.v4.GetProfileReq")
	proto.RegisterType((*Profile)(nil), "xmux.core.user.v4.Profile")
	proto.RegisterType((*RefreshDeviceReq)(nil), "xmux.core.user.v4.RefreshDeviceReq")
	proto.RegisterType((*GetDevicesResp)(nil), "xmux.core.user.v4.GetDevicesResp")
	proto.RegisterType((*GetDevicesResp_Device)(nil), "xmux.core.user.v4.GetDevicesResp.Device")
}

func init() {
	proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7)
}

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x4d, 0x9a, 0xa4, 0x13, 0x35, 0x84, 0x15, 0x54, 0x91, 0x41, 0x25, 0x35, 0x97, 0x5c,
	0xd8, 0x48, 0x29, 0xe2, 0x86, 0x90, 0x0a, 0x55, 0xf9, 0x28, 0xa8, 0x32, 0xe9, 0x85, 0xdb, 0x36,
	0x99, 0x24, 0x2b, 0x6c, 0xaf, 0xf1, 0xae, 0xa3, 0xe6, 0xcf, 0xf0, 0x1f, 0x10, 0xbf, 0x8d, 0x23,
	0x12, 0xde, 0xb5, 0x9d, 0xb8, 0x89, 0xa3, 0x70, 0xe1, 0x12, 0xed, 0xbc, 0x9d, 0x79, 0x7e, 0x33,
	0x3b, 0x2f, 0xf0, 0x28, 0x8c, 0x84, 0x12, 0xfd, 0x58, 0x62, 0x64, 0x7e, 0xa8, 0x89, 0xc9, 0x83,
	0x5b, 0x3f, 0xbe, 0xa5, 0x23, 0x11, 0x21, 0x35, 0xe8, 0xfc, 0x85, 0xfd, 0x78, 0x2a, 0xc4, 0xd4,
	0xc3, 0xbe, 0x49, 0xb8, 0x89, 0x27, 0x7d, 0xf4, 0x43, 0xb5, 0x48, 0xf3, 0xed, 0xa7, 0xeb, 0x97,
	0x8a, 0xfb, 0x28, 0x15, 0xf3, 0xc3, 0x34, 0xc1, 0x39, 0x87, 0xa6, 0x8b, 0x53, 0x2e, 0x15, 0x46,
	0x2e, 0x7e, 0x27, 0x5d, 0x68, 0x8e, 0xb9, 0x0c, 0x3d, 0xb6, 0xf8, 0xcc, 0x7c, 0xec, 0x58, 0x5d,
	0xab, 0x77, 0xe0, 0x16, 0x21, 0xf2, 0x10, 0xf6, 0xd1, 0x67, 0xdc, 0xeb, 0xec, 0x99, 0xbb, 0x34,
	0x70, 0x9e, 0xc3, 0xc1, 0xa5, 0x98, 0xf2, 0xc0, 0x45, 0x19, 0x6a, 0x92, 0x51, 0x2c, 0x95, 0xf0,
	0x87, 0xe2, 0x1b, 0x06, 0x39, 0x49, 0x01, 0x72, 0x4e, 0xe0, 0xf0, 0x02, 0xd5, 0x55, 0x24, 0x26,
	0xdc, 0x43, 0xfd, 0xdd, 0x36, 0x54, 0x62, 0x3e, 0xce, 0x52, 0xf5, 0xd1, 0xf9, 0x69, 0x41, 0x3d,
	0x4b, 0xd8, 0xbc, 0x2d, 0x57, 0xb1, 0xae, 0xbe, 0xb2, 0xa9, 0xfe, 0x08, 0x6a, 0x6c, 0xce, 0x14,
	0x8b, 0x3a, 0x55, 0x73, 0x99, 0x45, 0x84, 0x40, 0x35, 0xd0, 0x25, 0xfb, 0x06, 0x35, 0x67, 0xcd,
	0x16, 0x30, 0xc5, 0x45, 0xc0, 0x3c, 0xae, 0x16, 0x9d, 0x5a, 0xca, 0x56, 0x80, 0x48, 0x0b, 0xf6,
	0x12, 0x59, 0x75, 0x73, 0x91, 0x9c, 0x9c, 0x3f, 0x16, 0xb4, 0x5d, 0x9c, 0x44, 0x28, 0x67, 0x6f,
	0x71, 0xce, 0x47, 0xa6, 0x35, 0x1b, 0x1a, 0x63, 0x13, 0xbc, 0xcf, 0x3b, 0x58, 0xc6, 0x46, 0xb0,
	0x39, 0x7f, 0x12, 0x63, 0xcc, 0x9b, 0x29, 0x42, 0xe4, 0x18, 0x20, 0x0d, 0x0b, 0x1d, 0x15, 0x10,
	0x72, 0x0d, 0xcd, 0x30, 0x96, 0xb3, 0x37, 0x33, 0x16, 0x04, 0x09, 0x83, 0xee, 0xaa, 0x35, 0x38,
	0xa5, 0x1b, 0x6b, 0x42, 0xd7, 0x75, 0xd1, 0xab, 0x55, 0xd9, 0x70, 0x11, 0xa2, 0x5b, 0xe4, 0x21,
	0x1d, 0xa8, 0xeb, 0xf0, 0x23, 0x2e, 0xb2, 0x91, 0xe4, 0xa1, 0x63, 0xc3, 0xfd, 0xb5, 0x4a, 0x52,
	0x87, 0xca, 0x64, 0xe4, 0xb7, 0xef, 0x39, 0xbf, 0x2d, 0x68, 0x25, 0xef, 0x9a, 0x7e, 0x43, 0x9a,
	0x5d, 0x38, 0x83, 0x7a, 0xaa, 0x56, 0x26, 0xcd, 0x57, 0x7a, 0xcd, 0x41, 0xaf, 0x44, 0xdb, 0xdd,
	0x1a, 0x9a, 0x69, 0xcc, 0x0b, 0xed, 0x1f, 0x16, 0xd4, 0x52, 0xec, 0x3f, 0x0f, 0xf3, 0x25, 0x34,
	0x3c, 0x26, 0xd5, 0x17, 0x4c, 0xb6, 0x56, 0x4f, 0xb2, 0x39, 0xb0, 0x69, 0x6a, 0x20, 0x9a, 0x1b,
	0x88, 0x0e, 0x73, 0x03, 0xb9, 0xcb, 0xdc, 0xc1, 0xaf, 0x0a, 0x54, 0xaf, 0x93, 0x5e, 0xc8, 0x2b,
	0xd8, 0x37, 0x36, 0x20, 0x47, 0x1b, 0x75, 0xe7, 0xda, 0x95, 0xf6, 0x93, 0x92, 0xee, 0x57, 0xc6,
	0x79, 0x07, 0x8d, 0xdc, 0x8c, 0xe4, 0xb8, 0xf4, 0x0d, 0x97, 0x4e, 0xdd, 0xc1, 0xf4, 0x01, 0x60,
	0x65, 0x30, 0xd2, 0x2d, 0x9f, 0xf9, 0xca, 0x7f, 0xb6, 0x5d, 0x92, 0x91, 0x57, 0x5f, 0xc2, 0xe1,
	0x9d, 0xe5, 0x21, 0xcf, 0xfe, 0x61, 0xbd, 0xec, 0x2d, 0x13, 0x20, 0x17, 0x46, 0x59, 0xf6, 0xdc,
	0x5b, 0xe7, 0x74, 0xb2, 0x73, 0x4b, 0xc8, 0x6b, 0x2d, 0x6b, 0x9e, 0xfc, 0x9d, 0xec, 0xe2, 0xda,
	0x82, 0x9f, 0xd5, 0xbe, 0x56, 0x35, 0xf5, 0x4d, 0xcd, 0xe0, 0xa7, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x29, 0x79, 0xe8, 0x30, 0x73, 0x05, 0x00, 0x00,
}
