// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: auth/v4/auth.proto

package v4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CampusRole int32

const (
	CampusRole_none    CampusRole = 0
	CampusRole_student CampusRole = 1
	CampusRole_teacher CampusRole = 2
)

// Enum value maps for CampusRole.
var (
	CampusRole_name = map[int32]string{
		0: "none",
		1: "student",
		2: "teacher",
	}
	CampusRole_value = map[string]int32{
		"none":    0,
		"student": 1,
		"teacher": 2,
	}
)

func (x CampusRole) Enum() *CampusRole {
	p := new(CampusRole)
	*p = x
	return p
}

func (x CampusRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CampusRole) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v4_auth_proto_enumTypes[0].Descriptor()
}

func (CampusRole) Type() protoreflect.EnumType {
	return &file_auth_v4_auth_proto_enumTypes[0]
}

func (x CampusRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CampusRole.Descriptor instead.
func (CampusRole) EnumDescriptor() ([]byte, []int) {
	return file_auth_v4_auth_proto_rawDescGZIP(), []int{0}
}

// Credential for authenticating user with campus ID and password.
type CampusIdPasswordCredential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CampusId string `protobuf:"bytes,1,opt,name=campusId,proto3" json:"campusId,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CampusIdPasswordCredential) Reset() {
	*x = CampusIdPasswordCredential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v4_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CampusIdPasswordCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampusIdPasswordCredential) ProtoMessage() {}

func (x *CampusIdPasswordCredential) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v4_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampusIdPasswordCredential.ProtoReflect.Descriptor instead.
func (*CampusIdPasswordCredential) Descriptor() ([]byte, []int) {
	return file_auth_v4_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CampusIdPasswordCredential) GetCampusId() string {
	if x != nil {
		return x.CampusId
	}
	return ""
}

func (x *CampusIdPasswordCredential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Credential:
	//	*AuthUserReq_CampusIdPassword
	//	*AuthUserReq_FirebaseIdToken
	Credential isAuthUserReq_Credential `protobuf_oneof:"credential"`
}

func (x *AuthUserReq) Reset() {
	*x = AuthUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v4_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserReq) ProtoMessage() {}

func (x *AuthUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v4_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserReq.ProtoReflect.Descriptor instead.
func (*AuthUserReq) Descriptor() ([]byte, []int) {
	return file_auth_v4_auth_proto_rawDescGZIP(), []int{1}
}

func (m *AuthUserReq) GetCredential() isAuthUserReq_Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (x *AuthUserReq) GetCampusIdPassword() *CampusIdPasswordCredential {
	if x, ok := x.GetCredential().(*AuthUserReq_CampusIdPassword); ok {
		return x.CampusIdPassword
	}
	return nil
}

func (x *AuthUserReq) GetFirebaseIdToken() string {
	if x, ok := x.GetCredential().(*AuthUserReq_FirebaseIdToken); ok {
		return x.FirebaseIdToken
	}
	return ""
}

type isAuthUserReq_Credential interface {
	isAuthUserReq_Credential()
}

type AuthUserReq_CampusIdPassword struct {
	// Authenticate user with campus ID and password.
	CampusIdPassword *CampusIdPasswordCredential `protobuf:"bytes,1,opt,name=campusIdPassword,proto3,oneof"`
}

type AuthUserReq_FirebaseIdToken struct {
	// Authenticate user with firebase ID token.
	FirebaseIdToken string `protobuf:"bytes,2,opt,name=firebaseIdToken,proto3,oneof"`
}

func (*AuthUserReq_CampusIdPassword) isAuthUserReq_Credential() {}

func (*AuthUserReq_FirebaseIdToken) isAuthUserReq_Credential() {}

type AuthUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CampusRole CampusRole `protobuf:"varint,2,opt,name=campusRole,proto3,enum=xmux.core.auth.v4.CampusRole" json:"campusRole,omitempty"`
}

func (x *AuthUserResp) Reset() {
	*x = AuthUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v4_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResp) ProtoMessage() {}

func (x *AuthUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v4_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResp.ProtoReflect.Descriptor instead.
func (*AuthUserResp) Descriptor() ([]byte, []int) {
	return file_auth_v4_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthUserResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AuthUserResp) GetCampusRole() CampusRole {
	if x != nil {
		return x.CampusRole
	}
	return CampusRole_none
}

var File_auth_v4_auth_proto protoreflect.FileDescriptor

var file_auth_v4_auth_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x34, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x78, 0x6d, 0x75, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x34, 0x22, 0x54, 0x0a, 0x1a, 0x43, 0x61, 0x6d, 0x70, 0x75,
	0x73, 0x49, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xa4, 0x01,
	0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x5b, 0x0a,
	0x10, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x49, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x78, 0x6d, 0x75, 0x78, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x34, 0x2e, 0x43, 0x61, 0x6d, 0x70,
	0x75, 0x73, 0x49, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x10, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73,
	0x49, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2a, 0x0a, 0x0f, 0x66, 0x69,
	0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0f, 0x66, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x49,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x0c, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x22, 0x5f, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x75, 0x73,
	0x52, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x78, 0x6d, 0x75,
	0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x34, 0x2e, 0x43,
	0x61, 0x6d, 0x70, 0x75, 0x73, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x75,
	0x73, 0x52, 0x6f, 0x6c, 0x65, 0x2a, 0x30, 0x0a, 0x0a, 0x43, 0x61, 0x6d, 0x70, 0x75, 0x73, 0x52,
	0x6f, 0x6c, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x74, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x10, 0x02, 0x32, 0x5b, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x4b, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x78, 0x6d, 0x75, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x34, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x78, 0x6d, 0x75, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x34, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x2e, 0x78, 0x64, 0x65, 0x61,
	0x2e, 0x78, 0x79, 0x7a, 0x2f, 0x58, 0x4d, 0x55, 0x53, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x34, 0x3b, 0x76, 0x34, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_v4_auth_proto_rawDescOnce sync.Once
	file_auth_v4_auth_proto_rawDescData = file_auth_v4_auth_proto_rawDesc
)

func file_auth_v4_auth_proto_rawDescGZIP() []byte {
	file_auth_v4_auth_proto_rawDescOnce.Do(func() {
		file_auth_v4_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_v4_auth_proto_rawDescData)
	})
	return file_auth_v4_auth_proto_rawDescData
}

var file_auth_v4_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v4_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_v4_auth_proto_goTypes = []interface{}{
	(CampusRole)(0),                    // 0: xmux.core.auth.v4.CampusRole
	(*CampusIdPasswordCredential)(nil), // 1: xmux.core.auth.v4.CampusIdPasswordCredential
	(*AuthUserReq)(nil),                // 2: xmux.core.auth.v4.AuthUserReq
	(*AuthUserResp)(nil),               // 3: xmux.core.auth.v4.AuthUserResp
}
var file_auth_v4_auth_proto_depIdxs = []int32{
	1, // 0: xmux.core.auth.v4.AuthUserReq.campusIdPassword:type_name -> xmux.core.auth.v4.CampusIdPasswordCredential
	0, // 1: xmux.core.auth.v4.AuthUserResp.campusRole:type_name -> xmux.core.auth.v4.CampusRole
	2, // 2: xmux.core.auth.v4.AuthInternal.AuthUser:input_type -> xmux.core.auth.v4.AuthUserReq
	3, // 3: xmux.core.auth.v4.AuthInternal.AuthUser:output_type -> xmux.core.auth.v4.AuthUserResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_v4_auth_proto_init() }
func file_auth_v4_auth_proto_init() {
	if File_auth_v4_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_v4_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CampusIdPasswordCredential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v4_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v4_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_auth_v4_auth_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AuthUserReq_CampusIdPassword)(nil),
		(*AuthUserReq_FirebaseIdToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_v4_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v4_auth_proto_goTypes,
		DependencyIndexes: file_auth_v4_auth_proto_depIdxs,
		EnumInfos:         file_auth_v4_auth_proto_enumTypes,
		MessageInfos:      file_auth_v4_auth_proto_msgTypes,
	}.Build()
	File_auth_v4_auth_proto = out.File
	file_auth_v4_auth_proto_rawDesc = nil
	file_auth_v4_auth_proto_goTypes = nil
	file_auth_v4_auth_proto_depIdxs = nil
}
