// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: xia/v4/xia.proto

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Xia_Chat_FullMethodName       = "/xmux.xia.v4.Xia/Chat"
	Xia_ChatStream_FullMethodName = "/xmux.xia.v4.Xia/ChatStream"
)

// XiaClient is the client API for Xia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XiaClient interface {
	Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
	ChatStream(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResp], error)
}

type xiaClient struct {
	cc grpc.ClientConnInterface
}

func NewXiaClient(cc grpc.ClientConnInterface) XiaClient {
	return &xiaClient{cc}
}

func (c *xiaClient) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResp)
	err := c.cc.Invoke(ctx, Xia_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xiaClient) ChatStream(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Xia_ServiceDesc.Streams[0], Xia_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatReq, ChatResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Xia_ChatStreamClient = grpc.ServerStreamingClient[ChatResp]

// XiaServer is the server API for Xia service.
// All implementations must embed UnimplementedXiaServer
// for forward compatibility.
type XiaServer interface {
	Chat(context.Context, *ChatReq) (*ChatResp, error)
	ChatStream(*ChatReq, grpc.ServerStreamingServer[ChatResp]) error
	mustEmbedUnimplementedXiaServer()
}

// UnimplementedXiaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXiaServer struct{}

func (UnimplementedXiaServer) Chat(context.Context, *ChatReq) (*ChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedXiaServer) ChatStream(*ChatReq, grpc.ServerStreamingServer[ChatResp]) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedXiaServer) mustEmbedUnimplementedXiaServer() {}
func (UnimplementedXiaServer) testEmbeddedByValue()             {}

// UnsafeXiaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XiaServer will
// result in compilation errors.
type UnsafeXiaServer interface {
	mustEmbedUnimplementedXiaServer()
}

func RegisterXiaServer(s grpc.ServiceRegistrar, srv XiaServer) {
	// If the following call pancis, it indicates UnimplementedXiaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Xia_ServiceDesc, srv)
}

func _Xia_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XiaServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Xia_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XiaServer).Chat(ctx, req.(*ChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xia_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XiaServer).ChatStream(m, &grpc.GenericServerStream[ChatReq, ChatResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Xia_ChatStreamServer = grpc.ServerStreamingServer[ChatResp]

// Xia_ServiceDesc is the grpc.ServiceDesc for Xia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Xia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmux.xia.v4.Xia",
	HandlerType: (*XiaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _Xia_Chat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _Xia_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xia/v4/xia.proto",
}
