// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v4

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsNoCustomToken(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NO_CUSTOM_TOKEN.String() && e.Code == 500
}

func ErrorNoCustomToken(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_NO_CUSTOM_TOKEN.String(), fmt.Sprintf(format, args...))
}

func IsNeedRegister(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_REGISTER.String() && e.Code == 500
}

func ErrorNeedRegister(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_NEED_REGISTER.String(), fmt.Sprintf(format, args...))
}
