// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: user/v4/user_internal.proto

package v4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNamesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []string `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *GetNamesReq) Reset() {
	*x = GetNamesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v4_user_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNamesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamesReq) ProtoMessage() {}

func (x *GetNamesReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v4_user_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamesReq.ProtoReflect.Descriptor instead.
func (*GetNamesReq) Descriptor() ([]byte, []int) {
	return file_user_v4_user_internal_proto_rawDescGZIP(), []int{0}
}

func (x *GetNamesReq) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type GetNamesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names map[string]string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetNamesResp) Reset() {
	*x = GetNamesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v4_user_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNamesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamesResp) ProtoMessage() {}

func (x *GetNamesResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_v4_user_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamesResp.ProtoReflect.Descriptor instead.
func (*GetNamesResp) Descriptor() ([]byte, []int) {
	return file_user_v4_user_internal_proto_rawDescGZIP(), []int{1}
}

func (x *GetNamesResp) GetNames() map[string]string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_user_v4_user_internal_proto protoreflect.FileDescriptor

var file_user_v4_user_internal_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x34, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x78,
	0x6d, 0x75, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x34,
	0x22, 0x21, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x69, 0x64, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x78, 0x6d, 0x75, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x34, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x32, 0x5b, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x12, 0x4b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x78,
	0x6d, 0x75, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x34,
	0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x78,
	0x6d, 0x75, 0x78, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x34,
	0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x2e, 0x78, 0x64, 0x65, 0x61, 0x2e, 0x78, 0x79, 0x7a, 0x2f, 0x58, 0x4d,
	0x55, 0x53, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2f, 0x76, 0x34, 0x3b, 0x76, 0x34, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_v4_user_internal_proto_rawDescOnce sync.Once
	file_user_v4_user_internal_proto_rawDescData = file_user_v4_user_internal_proto_rawDesc
)

func file_user_v4_user_internal_proto_rawDescGZIP() []byte {
	file_user_v4_user_internal_proto_rawDescOnce.Do(func() {
		file_user_v4_user_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_v4_user_internal_proto_rawDescData)
	})
	return file_user_v4_user_internal_proto_rawDescData
}

var file_user_v4_user_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_v4_user_internal_proto_goTypes = []interface{}{
	(*GetNamesReq)(nil),  // 0: xmux.core.user.v4.GetNamesReq
	(*GetNamesResp)(nil), // 1: xmux.core.user.v4.GetNamesResp
	nil,                  // 2: xmux.core.user.v4.GetNamesResp.NamesEntry
}
var file_user_v4_user_internal_proto_depIdxs = []int32{
	2, // 0: xmux.core.user.v4.GetNamesResp.names:type_name -> xmux.core.user.v4.GetNamesResp.NamesEntry
	0, // 1: xmux.core.user.v4.UserInternal.GetNames:input_type -> xmux.core.user.v4.GetNamesReq
	1, // 2: xmux.core.user.v4.UserInternal.GetNames:output_type -> xmux.core.user.v4.GetNamesResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v4_user_internal_proto_init() }
func file_user_v4_user_internal_proto_init() {
	if File_user_v4_user_internal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_v4_user_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNamesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_v4_user_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNamesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_v4_user_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v4_user_internal_proto_goTypes,
		DependencyIndexes: file_user_v4_user_internal_proto_depIdxs,
		MessageInfos:      file_user_v4_user_internal_proto_msgTypes,
	}.Build()
	File_user_v4_user_internal_proto = out.File
	file_user_v4_user_internal_proto_rawDesc = nil
	file_user_v4_user_internal_proto_goTypes = nil
	file_user_v4_user_internal_proto_depIdxs = nil
}
