// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/aaos/aaos.proto

package aaos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Info_Gender int32

const (
	Info_male   Info_Gender = 0
	Info_female Info_Gender = 1
)

var Info_Gender_name = map[int32]string{
	0: "male",
	1: "female",
}

var Info_Gender_value = map[string]int32{
	"male":   0,
	"female": 1,
}

func (x Info_Gender) String() string {
	return proto.EnumName(Info_Gender_name, int32(x))
}

func (Info_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{0, 0}
}

type Info struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender               Info_Gender          `protobuf:"varint,2,opt,name=gender,proto3,enum=xmux.core.aaos.v4.Info_Gender" json:"gender,omitempty"`
	Id                   string               `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Programme            string               `protobuf:"bytes,4,opt,name=programme,proto3" json:"programme,omitempty"`
	Intake               *timestamp.Timestamp `protobuf:"bytes,5,opt,name=intake,proto3" json:"intake,omitempty"`
	Nationality          string               `protobuf:"bytes,6,opt,name=nationality,proto3" json:"nationality,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{0}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Info) GetGender() Info_Gender {
	if m != nil {
		return m.Gender
	}
	return Info_male
}

func (m *Info) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Info) GetProgramme() string {
	if m != nil {
		return m.Programme
	}
	return ""
}

func (m *Info) GetIntake() *timestamp.Timestamp {
	if m != nil {
		return m.Intake
	}
	return nil
}

func (m *Info) GetNationality() string {
	if m != nil {
		return m.Nationality
	}
	return ""
}

type Timetable struct {
	Classes              []*Timetable_Class   `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	LastUpdate           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Timetable) Reset()         { *m = Timetable{} }
func (m *Timetable) String() string { return proto.CompactTextString(m) }
func (*Timetable) ProtoMessage()    {}
func (*Timetable) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{1}
}

func (m *Timetable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timetable.Unmarshal(m, b)
}
func (m *Timetable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timetable.Marshal(b, m, deterministic)
}
func (m *Timetable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timetable.Merge(m, src)
}
func (m *Timetable) XXX_Size() int {
	return xxx_messageInfo_Timetable.Size(m)
}
func (m *Timetable) XXX_DiscardUnknown() {
	xxx_messageInfo_Timetable.DiscardUnknown(m)
}

var xxx_messageInfo_Timetable proto.InternalMessageInfo

func (m *Timetable) GetClasses() []*Timetable_Class {
	if m != nil {
		return m.Classes
	}
	return nil
}

func (m *Timetable) GetLastUpdate() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdate
	}
	return nil
}

type Timetable_Class struct {
	Cid      string               `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Name     string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lecturer string               `protobuf:"bytes,3,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
	Room     string               `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	Begin    *timestamp.Timestamp `protobuf:"bytes,5,opt,name=begin,proto3" json:"begin,omitempty"`
	End      *timestamp.Timestamp `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	// Day of week. Start from 1 (Monday).
	Day                  uint32   `protobuf:"varint,7,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timetable_Class) Reset()         { *m = Timetable_Class{} }
func (m *Timetable_Class) String() string { return proto.CompactTextString(m) }
func (*Timetable_Class) ProtoMessage()    {}
func (*Timetable_Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{1, 0}
}

func (m *Timetable_Class) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timetable_Class.Unmarshal(m, b)
}
func (m *Timetable_Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timetable_Class.Marshal(b, m, deterministic)
}
func (m *Timetable_Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timetable_Class.Merge(m, src)
}
func (m *Timetable_Class) XXX_Size() int {
	return xxx_messageInfo_Timetable_Class.Size(m)
}
func (m *Timetable_Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Timetable_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Timetable_Class proto.InternalMessageInfo

func (m *Timetable_Class) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Timetable_Class) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Timetable_Class) GetLecturer() string {
	if m != nil {
		return m.Lecturer
	}
	return ""
}

func (m *Timetable_Class) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *Timetable_Class) GetBegin() *timestamp.Timestamp {
	if m != nil {
		return m.Begin
	}
	return nil
}

func (m *Timetable_Class) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Timetable_Class) GetDay() uint32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type Courses struct {
	Courses              []*Courses_Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Courses) Reset()         { *m = Courses{} }
func (m *Courses) String() string { return proto.CompactTextString(m) }
func (*Courses) ProtoMessage()    {}
func (*Courses) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{2}
}

func (m *Courses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Courses.Unmarshal(m, b)
}
func (m *Courses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Courses.Marshal(b, m, deterministic)
}
func (m *Courses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Courses.Merge(m, src)
}
func (m *Courses) XXX_Size() int {
	return xxx_messageInfo_Courses.Size(m)
}
func (m *Courses) XXX_DiscardUnknown() {
	xxx_messageInfo_Courses.DiscardUnknown(m)
}

var xxx_messageInfo_Courses proto.InternalMessageInfo

func (m *Courses) GetCourses() []*Courses_Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type Courses_Course struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Credit               uint32   `protobuf:"varint,2,opt,name=credit,proto3" json:"credit,omitempty"`
	Lecturer             string   `protobuf:"bytes,3,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Courses_Course) Reset()         { *m = Courses_Course{} }
func (m *Courses_Course) String() string { return proto.CompactTextString(m) }
func (*Courses_Course) ProtoMessage()    {}
func (*Courses_Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{2, 0}
}

func (m *Courses_Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Courses_Course.Unmarshal(m, b)
}
func (m *Courses_Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Courses_Course.Marshal(b, m, deterministic)
}
func (m *Courses_Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Courses_Course.Merge(m, src)
}
func (m *Courses_Course) XXX_Size() int {
	return xxx_messageInfo_Courses_Course.Size(m)
}
func (m *Courses_Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Courses_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Courses_Course proto.InternalMessageInfo

func (m *Courses_Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Courses_Course) GetCredit() uint32 {
	if m != nil {
		return m.Credit
	}
	return 0
}

func (m *Courses_Course) GetLecturer() string {
	if m != nil {
		return m.Lecturer
	}
	return ""
}

type Exams struct {
	Exams                []*Exams_Exam        `protobuf:"bytes,1,rep,name=exams,proto3" json:"exams,omitempty"`
	LastUpdate           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Exams) Reset()         { *m = Exams{} }
func (m *Exams) String() string { return proto.CompactTextString(m) }
func (*Exams) ProtoMessage()    {}
func (*Exams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{3}
}

func (m *Exams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exams.Unmarshal(m, b)
}
func (m *Exams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exams.Marshal(b, m, deterministic)
}
func (m *Exams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exams.Merge(m, src)
}
func (m *Exams) XXX_Size() int {
	return xxx_messageInfo_Exams.Size(m)
}
func (m *Exams) XXX_DiscardUnknown() {
	xxx_messageInfo_Exams.DiscardUnknown(m)
}

var xxx_messageInfo_Exams proto.InternalMessageInfo

func (m *Exams) GetExams() []*Exams_Exam {
	if m != nil {
		return m.Exams
	}
	return nil
}

func (m *Exams) GetLastUpdate() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdate
	}
	return nil
}

type Exams_Exam struct {
	Exam                 string               `protobuf:"bytes,1,opt,name=exam,proto3" json:"exam,omitempty"`
	Begin                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Venue                string               `protobuf:"bytes,4,opt,name=venue,proto3" json:"venue,omitempty"`
	CourseName           string               `protobuf:"bytes,5,opt,name=courseName,proto3" json:"courseName,omitempty"`
	Type                 string               `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Exams_Exam) Reset()         { *m = Exams_Exam{} }
func (m *Exams_Exam) String() string { return proto.CompactTextString(m) }
func (*Exams_Exam) ProtoMessage()    {}
func (*Exams_Exam) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{3, 0}
}

func (m *Exams_Exam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exams_Exam.Unmarshal(m, b)
}
func (m *Exams_Exam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exams_Exam.Marshal(b, m, deterministic)
}
func (m *Exams_Exam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exams_Exam.Merge(m, src)
}
func (m *Exams_Exam) XXX_Size() int {
	return xxx_messageInfo_Exams_Exam.Size(m)
}
func (m *Exams_Exam) XXX_DiscardUnknown() {
	xxx_messageInfo_Exams_Exam.DiscardUnknown(m)
}

var xxx_messageInfo_Exams_Exam proto.InternalMessageInfo

func (m *Exams_Exam) GetExam() string {
	if m != nil {
		return m.Exam
	}
	return ""
}

func (m *Exams_Exam) GetBegin() *timestamp.Timestamp {
	if m != nil {
		return m.Begin
	}
	return nil
}

func (m *Exams_Exam) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Exams_Exam) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *Exams_Exam) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *Exams_Exam) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Exams_Exam) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Transcript struct {
	Sessions             []*Transcript_Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Transcript) Reset()         { *m = Transcript{} }
func (m *Transcript) String() string { return proto.CompactTextString(m) }
func (*Transcript) ProtoMessage()    {}
func (*Transcript) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{4}
}

func (m *Transcript) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transcript.Unmarshal(m, b)
}
func (m *Transcript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transcript.Marshal(b, m, deterministic)
}
func (m *Transcript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transcript.Merge(m, src)
}
func (m *Transcript) XXX_Size() int {
	return xxx_messageInfo_Transcript.Size(m)
}
func (m *Transcript) XXX_DiscardUnknown() {
	xxx_messageInfo_Transcript.DiscardUnknown(m)
}

var xxx_messageInfo_Transcript proto.InternalMessageInfo

func (m *Transcript) GetSessions() []*Transcript_Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type Transcript_Session struct {
	Session              string                       `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Courses              []*Transcript_Session_Course `protobuf:"bytes,2,rep,name=courses,proto3" json:"courses,omitempty"`
	Gpa                  float32                      `protobuf:"fixed32,3,opt,name=gpa,proto3" json:"gpa,omitempty"`
	CGpa                 float32                      `protobuf:"fixed32,4,opt,name=cGpa,proto3" json:"cGpa,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Transcript_Session) Reset()         { *m = Transcript_Session{} }
func (m *Transcript_Session) String() string { return proto.CompactTextString(m) }
func (*Transcript_Session) ProtoMessage()    {}
func (*Transcript_Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{4, 0}
}

func (m *Transcript_Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transcript_Session.Unmarshal(m, b)
}
func (m *Transcript_Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transcript_Session.Marshal(b, m, deterministic)
}
func (m *Transcript_Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transcript_Session.Merge(m, src)
}
func (m *Transcript_Session) XXX_Size() int {
	return xxx_messageInfo_Transcript_Session.Size(m)
}
func (m *Transcript_Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Transcript_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Transcript_Session proto.InternalMessageInfo

func (m *Transcript_Session) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *Transcript_Session) GetCourses() []*Transcript_Session_Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

func (m *Transcript_Session) GetGpa() float32 {
	if m != nil {
		return m.Gpa
	}
	return 0
}

func (m *Transcript_Session) GetCGpa() float32 {
	if m != nil {
		return m.CGpa
	}
	return 0
}

type Transcript_Session_Course struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Credit               uint32   `protobuf:"varint,3,opt,name=credit,proto3" json:"credit,omitempty"`
	Grade                string   `protobuf:"bytes,4,opt,name=grade,proto3" json:"grade,omitempty"`
	Point                float32  `protobuf:"fixed32,5,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transcript_Session_Course) Reset()         { *m = Transcript_Session_Course{} }
func (m *Transcript_Session_Course) String() string { return proto.CompactTextString(m) }
func (*Transcript_Session_Course) ProtoMessage()    {}
func (*Transcript_Session_Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30284bad2947520, []int{4, 0, 0}
}

func (m *Transcript_Session_Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transcript_Session_Course.Unmarshal(m, b)
}
func (m *Transcript_Session_Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transcript_Session_Course.Marshal(b, m, deterministic)
}
func (m *Transcript_Session_Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transcript_Session_Course.Merge(m, src)
}
func (m *Transcript_Session_Course) XXX_Size() int {
	return xxx_messageInfo_Transcript_Session_Course.Size(m)
}
func (m *Transcript_Session_Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Transcript_Session_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Transcript_Session_Course proto.InternalMessageInfo

func (m *Transcript_Session_Course) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Transcript_Session_Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Transcript_Session_Course) GetCredit() uint32 {
	if m != nil {
		return m.Credit
	}
	return 0
}

func (m *Transcript_Session_Course) GetGrade() string {
	if m != nil {
		return m.Grade
	}
	return ""
}

func (m *Transcript_Session_Course) GetPoint() float32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func init() {
	proto.RegisterEnum("xmux.core.aaos.v4.Info_Gender", Info_Gender_name, Info_Gender_value)
	proto.RegisterType((*Info)(nil), "xmux.core.aaos.v4.Info")
	proto.RegisterType((*Timetable)(nil), "xmux.core.aaos.v4.Timetable")
	proto.RegisterType((*Timetable_Class)(nil), "xmux.core.aaos.v4.Timetable.Class")
	proto.RegisterType((*Courses)(nil), "xmux.core.aaos.v4.Courses")
	proto.RegisterType((*Courses_Course)(nil), "xmux.core.aaos.v4.Courses.Course")
	proto.RegisterType((*Exams)(nil), "xmux.core.aaos.v4.Exams")
	proto.RegisterType((*Exams_Exam)(nil), "xmux.core.aaos.v4.Exams.Exam")
	proto.RegisterType((*Transcript)(nil), "xmux.core.aaos.v4.Transcript")
	proto.RegisterType((*Transcript_Session)(nil), "xmux.core.aaos.v4.Transcript.Session")
	proto.RegisterType((*Transcript_Session_Course)(nil), "xmux.core.aaos.v4.Transcript.Session.Course")
}

func init() {
	proto.RegisterFile("proto/aaos/aaos.proto", fileDescriptor_e30284bad2947520)
}

var fileDescriptor_e30284bad2947520 = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x26, 0x8e, 0xed, 0x24, 0x53, 0x5a, 0x95, 0x15, 0x14, 0xcb, 0xb4, 0xa5, 0x44, 0x42, 0xe2,
	0x50, 0xb9, 0x28, 0x45, 0x1c, 0x80, 0x03, 0xa5, 0x94, 0x8a, 0x0b, 0x20, 0xb7, 0x5c, 0xb8, 0x6d,
	0xec, 0x6d, 0x64, 0x11, 0xff, 0xc8, 0xde, 0x54, 0xcd, 0x13, 0xf0, 0x0a, 0xbc, 0x15, 0xdc, 0x10,
	0x12, 0xcf, 0xc1, 0x99, 0xd9, 0x59, 0xdb, 0x09, 0x6d, 0x1c, 0x15, 0x71, 0x49, 0x66, 0xc7, 0xdf,
	0xcc, 0xce, 0x7e, 0xdf, 0xcc, 0xc0, 0x9d, 0x2c, 0x4f, 0x65, 0xba, 0xc7, 0x79, 0x5a, 0xd0, 0x8f,
	0x47, 0x67, 0x76, 0xeb, 0x22, 0x9e, 0x5c, 0x78, 0x41, 0x9a, 0x0b, 0x8f, 0xbc, 0xe7, 0x4f, 0xdc,
	0x7b, 0xa3, 0x34, 0x1d, 0x8d, 0xc5, 0x1e, 0x01, 0x86, 0x93, 0xb3, 0x3d, 0x11, 0x67, 0x72, 0xaa,
	0xf1, 0xee, 0xfd, 0xcb, 0x1f, 0x65, 0x14, 0x8b, 0x42, 0xf2, 0x38, 0xd3, 0x80, 0xfe, 0xef, 0x16,
	0x98, 0x6f, 0x93, 0xb3, 0x94, 0x31, 0x30, 0x13, 0x1e, 0x0b, 0xa7, 0xb5, 0xd3, 0x7a, 0xd4, 0xf3,
	0xc9, 0x66, 0x4f, 0xc1, 0x1e, 0x89, 0x24, 0x14, 0xb9, 0x63, 0xa0, 0x77, 0x6d, 0xb0, 0xed, 0x5d,
	0xb9, 0xde, 0x53, 0xc1, 0xde, 0x31, 0xa1, 0xfc, 0x12, 0xcd, 0xd6, 0xc0, 0x88, 0x42, 0xa7, 0x4d,
	0x99, 0xd0, 0x62, 0x9b, 0xd0, 0xc3, 0xdb, 0x46, 0x39, 0x8f, 0xf1, 0x02, 0x93, 0xdc, 0x33, 0x07,
	0x1b, 0x80, 0x1d, 0x25, 0x92, 0x7f, 0x16, 0x8e, 0x85, 0x9f, 0x56, 0x06, 0xae, 0xa7, 0x8b, 0xf6,
	0xaa, 0xa2, 0xbd, 0xd3, 0xaa, 0x68, 0xbf, 0x44, 0xb2, 0x1d, 0x58, 0x49, 0xb8, 0x8c, 0xd2, 0x84,
	0x8f, 0x23, 0x39, 0x75, 0x6c, 0xca, 0x39, 0xef, 0xea, 0x6f, 0x83, 0xad, 0xab, 0x62, 0x5d, 0x30,
	0x63, 0x3e, 0x16, 0xeb, 0x37, 0x18, 0x80, 0x7d, 0x26, 0xc8, 0x6e, 0xf5, 0x7f, 0x18, 0xd0, 0x53,
	0x79, 0x25, 0x1f, 0x8e, 0x05, 0x7b, 0x01, 0x9d, 0x60, 0xcc, 0x8b, 0x42, 0x14, 0x48, 0x40, 0x1b,
	0x8b, 0xe8, 0x2f, 0x78, 0x6a, 0x0d, 0xf7, 0x0e, 0x15, 0xd6, 0xaf, 0x42, 0xd8, 0x33, 0x00, 0xb4,
	0xe4, 0xc7, 0x2c, 0xe4, 0x52, 0x10, 0x57, 0xcb, 0x5f, 0x31, 0x87, 0x76, 0xbf, 0xb5, 0xc0, 0xa2,
	0x74, 0x6c, 0x1d, 0xda, 0x01, 0xd2, 0xa6, 0x05, 0x50, 0x66, 0xad, 0x89, 0x31, 0xa7, 0x89, 0x0b,
	0xdd, 0xb1, 0x08, 0xe4, 0x24, 0x47, 0x55, 0x34, 0xc3, 0xf5, 0x59, 0xe1, 0xf3, 0x34, 0x8d, 0x4b,
	0x8a, 0xc9, 0x66, 0x8f, 0xc1, 0x1a, 0x8a, 0x51, 0x94, 0x5c, 0x83, 0x5c, 0x0d, 0x64, 0xbb, 0xd0,
	0x46, 0xe2, 0x88, 0xd3, 0xe5, 0x78, 0x05, 0x53, 0x55, 0x87, 0x7c, 0xea, 0x74, 0x10, 0xbd, 0xea,
	0x2b, 0xb3, 0xff, 0xb5, 0x05, 0x9d, 0xc3, 0x74, 0x92, 0x2b, 0x66, 0x9e, 0x23, 0xaf, 0xda, 0x2c,
	0x79, 0x7d, 0xb0, 0x80, 0xd7, 0x12, 0x5c, 0xfe, 0xfb, 0x55, 0x84, 0xfb, 0x01, 0x6c, 0xed, 0x5a,
	0xd8, 0x9c, 0x1b, 0x60, 0x07, 0xb9, 0x08, 0x23, 0x49, 0xf4, 0xac, 0xfa, 0xe5, 0x69, 0x19, 0x41,
	0x4a, 0x74, 0xeb, 0xe8, 0x82, 0xc7, 0x05, 0xdb, 0x07, 0x4b, 0x28, 0xa3, 0x2c, 0x6b, 0x6b, 0x41,
	0x59, 0x04, 0xa4, 0x5f, 0x5f, 0x63, 0xff, 0x4b, 0xe7, 0x5f, 0x38, 0x68, 0x2a, 0x97, 0x7a, 0x8b,
	0xca, 0x56, 0xbd, 0x45, 0xd9, 0x33, 0x91, 0x8c, 0x7f, 0x14, 0xa9, 0x7d, 0x3d, 0x91, 0x6e, 0x83,
	0x75, 0x2e, 0x92, 0x49, 0x35, 0x7c, 0xfa, 0xc0, 0xb6, 0x01, 0x34, 0xd5, 0xef, 0x14, 0xb7, 0x16,
	0x7d, 0x9a, 0xf3, 0xa8, 0x4a, 0xe5, 0x34, 0x13, 0xe5, 0x74, 0x91, 0xad, 0x58, 0xc7, 0xbc, 0x72,
	0x52, 0x90, 0xe2, 0x3d, 0xbf, 0x3c, 0xf5, 0x7f, 0x1a, 0x00, 0xa7, 0x39, 0x4f, 0x8a, 0x20, 0x8f,
	0x32, 0xc9, 0x0e, 0xa0, 0x8b, 0x0a, 0x16, 0x38, 0x8d, 0x15, 0xc3, 0x0f, 0x17, 0x0d, 0x54, 0x1d,
	0xe0, 0x9d, 0x68, 0xb4, 0x5f, 0x87, 0xb9, 0x5f, 0x0c, 0xe8, 0x94, 0x5e, 0xe6, 0x40, 0xa7, 0xf4,
	0x97, 0xb4, 0x55, 0x47, 0xf6, 0x66, 0xd6, 0x60, 0x06, 0xdd, 0xb3, 0x7b, 0xad, 0x7b, 0x2e, 0xf7,
	0x9a, 0x6a, 0xe3, 0x51, 0xc6, 0x89, 0x4f, 0xc3, 0x57, 0xa6, 0x7a, 0x7d, 0x70, 0x8c, 0x2e, 0x93,
	0x5c, 0x64, 0xbb, 0x72, 0xbe, 0x23, 0x83, 0x34, 0xac, 0x3b, 0x52, 0xd9, 0x0b, 0xc7, 0x75, 0xd6,
	0xa5, 0xed, 0xbf, 0xba, 0x14, 0x15, 0xc1, 0xf5, 0x17, 0xd6, 0x8a, 0xd0, 0x41, 0x79, 0xb3, 0x14,
	0x57, 0x1c, 0x89, 0x61, 0xf8, 0xfa, 0x30, 0xf8, 0x6e, 0x80, 0x79, 0x70, 0xf0, 0xfe, 0x04, 0xfb,
	0xaf, 0x73, 0x2c, 0x24, 0xad, 0xeb, 0x8d, 0x2b, 0x92, 0x1f, 0xa9, 0xb5, 0xef, 0xde, 0x6d, 0x58,
	0xd1, 0xec, 0x35, 0xdc, 0xc4, 0xd8, 0xd9, 0xc6, 0x6b, 0x4a, 0xb0, 0xb9, 0x6c, 0xf1, 0xb1, 0x97,
	0x00, 0x98, 0xa5, 0x9a, 0xee, 0xa6, 0x1c, 0x6e, 0xf3, 0x90, 0xe3, 0xa6, 0xed, 0x62, 0x06, 0x3d,
	0x84, 0x4d, 0xf1, 0x4e, 0xd3, 0x34, 0xa2, 0xdc, 0xab, 0xea, 0x15, 0xb3, 0x46, 0x6b, 0x4a, 0xb1,
	0xb5, 0xb4, 0x0d, 0x5e, 0xd9, 0x9f, 0x4c, 0xe5, 0x1d, 0xda, 0x14, 0xb6, 0xff, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x7e, 0xb7, 0x8f, 0x89, 0x6f, 0x07, 0x00, 0x00,
}
