// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CampusRole int32

const (
	CampusRole_none    CampusRole = 0
	CampusRole_student CampusRole = 1
	CampusRole_teacher CampusRole = 2
)

var CampusRole_name = map[int32]string{
	0: "none",
	1: "student",
	2: "teacher",
}

var CampusRole_value = map[string]int32{
	"none":    0,
	"student": 1,
	"teacher": 2,
}

func (x CampusRole) String() string {
	return proto.EnumName(CampusRole_name, int32(x))
}

func (CampusRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

// Credential for authenticating user with campus ID and password.
type CampusIdPasswordCredential struct {
	CampusId             string   `protobuf:"bytes,1,opt,name=campusId,proto3" json:"campusId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampusIdPasswordCredential) Reset()         { *m = CampusIdPasswordCredential{} }
func (m *CampusIdPasswordCredential) String() string { return proto.CompactTextString(m) }
func (*CampusIdPasswordCredential) ProtoMessage()    {}
func (*CampusIdPasswordCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *CampusIdPasswordCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampusIdPasswordCredential.Unmarshal(m, b)
}
func (m *CampusIdPasswordCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampusIdPasswordCredential.Marshal(b, m, deterministic)
}
func (m *CampusIdPasswordCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampusIdPasswordCredential.Merge(m, src)
}
func (m *CampusIdPasswordCredential) XXX_Size() int {
	return xxx_messageInfo_CampusIdPasswordCredential.Size(m)
}
func (m *CampusIdPasswordCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_CampusIdPasswordCredential.DiscardUnknown(m)
}

var xxx_messageInfo_CampusIdPasswordCredential proto.InternalMessageInfo

func (m *CampusIdPasswordCredential) GetCampusId() string {
	if m != nil {
		return m.CampusId
	}
	return ""
}

func (m *CampusIdPasswordCredential) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthUserReq struct {
	// Types that are valid to be assigned to Credential:
	//	*AuthUserReq_CampusIdPassword
	//	*AuthUserReq_FirebaseIdToken
	Credential           isAuthUserReq_Credential `protobuf_oneof:"credential"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AuthUserReq) Reset()         { *m = AuthUserReq{} }
func (m *AuthUserReq) String() string { return proto.CompactTextString(m) }
func (*AuthUserReq) ProtoMessage()    {}
func (*AuthUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *AuthUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserReq.Unmarshal(m, b)
}
func (m *AuthUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserReq.Marshal(b, m, deterministic)
}
func (m *AuthUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserReq.Merge(m, src)
}
func (m *AuthUserReq) XXX_Size() int {
	return xxx_messageInfo_AuthUserReq.Size(m)
}
func (m *AuthUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserReq proto.InternalMessageInfo

type isAuthUserReq_Credential interface {
	isAuthUserReq_Credential()
}

type AuthUserReq_CampusIdPassword struct {
	CampusIdPassword *CampusIdPasswordCredential `protobuf:"bytes,1,opt,name=campusIdPassword,proto3,oneof"`
}

type AuthUserReq_FirebaseIdToken struct {
	FirebaseIdToken string `protobuf:"bytes,2,opt,name=firebaseIdToken,proto3,oneof"`
}

func (*AuthUserReq_CampusIdPassword) isAuthUserReq_Credential() {}

func (*AuthUserReq_FirebaseIdToken) isAuthUserReq_Credential() {}

func (m *AuthUserReq) GetCredential() isAuthUserReq_Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *AuthUserReq) GetCampusIdPassword() *CampusIdPasswordCredential {
	if x, ok := m.GetCredential().(*AuthUserReq_CampusIdPassword); ok {
		return x.CampusIdPassword
	}
	return nil
}

func (m *AuthUserReq) GetFirebaseIdToken() string {
	if x, ok := m.GetCredential().(*AuthUserReq_FirebaseIdToken); ok {
		return x.FirebaseIdToken
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AuthUserReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AuthUserReq_CampusIdPassword)(nil),
		(*AuthUserReq_FirebaseIdToken)(nil),
	}
}

type AuthUserResp struct {
	Uid                  string                     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CampusRole           CampusRole                 `protobuf:"varint,2,opt,name=campusRole,proto3,enum=xmux.core.auth.v4.CampusRole" json:"campusRole,omitempty"`
	Permissions          map[string]*PermissionSpec `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AuthUserResp) Reset()         { *m = AuthUserResp{} }
func (m *AuthUserResp) String() string { return proto.CompactTextString(m) }
func (*AuthUserResp) ProtoMessage()    {}
func (*AuthUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *AuthUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserResp.Unmarshal(m, b)
}
func (m *AuthUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserResp.Marshal(b, m, deterministic)
}
func (m *AuthUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserResp.Merge(m, src)
}
func (m *AuthUserResp) XXX_Size() int {
	return xxx_messageInfo_AuthUserResp.Size(m)
}
func (m *AuthUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserResp proto.InternalMessageInfo

func (m *AuthUserResp) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AuthUserResp) GetCampusRole() CampusRole {
	if m != nil {
		return m.CampusRole
	}
	return CampusRole_none
}

func (m *AuthUserResp) GetPermissions() map[string]*PermissionSpec {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type PermissionSpec struct {
	Actions              []string `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionSpec) Reset()         { *m = PermissionSpec{} }
func (m *PermissionSpec) String() string { return proto.CompactTextString(m) }
func (*PermissionSpec) ProtoMessage()    {}
func (*PermissionSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *PermissionSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionSpec.Unmarshal(m, b)
}
func (m *PermissionSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionSpec.Marshal(b, m, deterministic)
}
func (m *PermissionSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionSpec.Merge(m, src)
}
func (m *PermissionSpec) XXX_Size() int {
	return xxx_messageInfo_PermissionSpec.Size(m)
}
func (m *PermissionSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionSpec proto.InternalMessageInfo

func (m *PermissionSpec) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterEnum("xmux.core.auth.v4.CampusRole", CampusRole_name, CampusRole_value)
	proto.RegisterType((*CampusIdPasswordCredential)(nil), "xmux.core.auth.v4.CampusIdPasswordCredential")
	proto.RegisterType((*AuthUserReq)(nil), "xmux.core.auth.v4.AuthUserReq")
	proto.RegisterType((*AuthUserResp)(nil), "xmux.core.auth.v4.AuthUserResp")
	proto.RegisterMapType((map[string]*PermissionSpec)(nil), "xmux.core.auth.v4.AuthUserResp.PermissionsEntry")
	proto.RegisterType((*PermissionSpec)(nil), "xmux.core.auth.v4.PermissionSpec")
}

func init() {
	proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5)
}

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0xdd, 0x8a, 0xda, 0x40,
	0x18, 0x35, 0xd1, 0xfa, 0xf3, 0x45, 0x6c, 0x3a, 0x50, 0x08, 0x81, 0xb6, 0x36, 0x57, 0x45, 0x68,
	0x2a, 0x69, 0xa1, 0xa5, 0xd0, 0x8b, 0x2a, 0x85, 0x4a, 0x6f, 0x64, 0xb4, 0x37, 0xed, 0xd5, 0x98,
	0xcc, 0x62, 0x50, 0x33, 0x71, 0x26, 0x71, 0xf5, 0x45, 0xf6, 0x09, 0xf6, 0x41, 0x37, 0x33, 0x31,
	0xc6, 0xf5, 0x67, 0xf7, 0x26, 0xcc, 0x99, 0xf3, 0x9d, 0xf3, 0x9d, 0x33, 0x04, 0x5e, 0xc7, 0x9c,
	0x25, 0xec, 0x13, 0x49, 0x93, 0xb9, 0xfa, 0xb8, 0x0a, 0xa3, 0x57, 0xdb, 0x55, 0xba, 0x75, 0x7d,
	0xc6, 0xa9, 0xab, 0x6e, 0x37, 0x5f, 0x9c, 0x29, 0xd8, 0x43, 0xb2, 0x8a, 0x53, 0x31, 0x0a, 0xc6,
	0x44, 0x88, 0x5b, 0xc6, 0x83, 0x21, 0xa7, 0x01, 0x8d, 0x92, 0x90, 0x2c, 0x91, 0x0d, 0x4d, 0x7f,
	0xcf, 0x5a, 0x5a, 0x57, 0xfb, 0xd0, 0xc2, 0x07, 0x2c, 0xb9, 0x78, 0xaf, 0xb0, 0xf4, 0x9c, 0x2b,
	0xb0, 0x73, 0xaf, 0x81, 0xf1, 0x33, 0xdb, 0xf0, 0x57, 0x50, 0x8e, 0xe9, 0x1a, 0xfd, 0x07, 0xd3,
	0x3f, 0xd9, 0xa2, 0xfc, 0x0c, 0xef, 0xa3, 0x7b, 0x96, 0xc9, 0xbd, 0x1e, 0xe8, 0x77, 0x05, 0x9f,
	0x19, 0xa1, 0x1e, 0xbc, 0xbc, 0x09, 0x39, 0x9d, 0x11, 0x41, 0x47, 0xc1, 0x94, 0x2d, 0x68, 0x94,
	0xe7, 0xc9, 0x86, 0x4f, 0x89, 0x41, 0x1b, 0xc0, 0x3f, 0xb8, 0x39, 0x77, 0x3a, 0xb4, 0xcb, 0x98,
	0x22, 0x46, 0x26, 0x54, 0xd3, 0xb0, 0xa8, 0x2a, 0x8f, 0xe8, 0x47, 0x26, 0x50, 0x0b, 0x31, 0x5b,
	0x52, 0xe5, 0xdb, 0xf1, 0xde, 0x5c, 0xcd, 0x2c, 0x87, 0xf0, 0x91, 0x00, 0x61, 0x30, 0x62, 0xca,
	0x57, 0xa1, 0x10, 0x21, 0x8b, 0x84, 0x55, 0xed, 0x56, 0xb3, 0xce, 0xfd, 0x0b, 0xfa, 0xe3, 0x18,
	0xee, 0xb8, 0x94, 0xfc, 0x8a, 0x12, 0xbe, 0xc3, 0xc7, 0x26, 0x36, 0x01, 0xf3, 0x74, 0x40, 0x06,
	0x5f, 0xd0, 0x5d, 0x11, 0x3c, 0x3b, 0xa2, 0xaf, 0xf0, 0x62, 0x43, 0x96, 0x69, 0x9e, 0xd9, 0xf0,
	0xde, 0x5f, 0xd8, 0x59, 0xba, 0x4c, 0x62, 0xea, 0xe3, 0x7c, 0xfe, 0xbb, 0xfe, 0x4d, 0x73, 0x7a,
	0xd0, 0x79, 0x4c, 0x22, 0x0b, 0x1a, 0xc4, 0x4f, 0x54, 0x09, 0x2d, 0x2b, 0xd1, 0xc2, 0x05, 0xec,
	0xf5, 0x01, 0xca, 0xf2, 0xa8, 0x09, 0xb5, 0x88, 0x45, 0xd4, 0xac, 0x20, 0x03, 0x1a, 0x22, 0x49,
	0xe5, 0x53, 0x9b, 0x9a, 0x04, 0x09, 0x25, 0xfe, 0x9c, 0x72, 0x53, 0xf7, 0x26, 0x50, 0x93, 0x75,
	0xd1, 0x1f, 0x68, 0x16, 0xb5, 0xd1, 0xdb, 0x27, 0xdf, 0x64, 0x6d, 0xbf, 0x7b, 0xe6, 0xcd, 0x06,
	0xf5, 0x7f, 0x35, 0x79, 0x3f, 0xab, 0xab, 0x5f, 0xfd, 0xf3, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xd5, 0x3a, 0x3d, 0x50, 0x03, 0x03, 0x00, 0x00,
}
