// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: oss/v4/error_reason.proto

package v4

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNKNOWN            ErrorReason = 0
	ErrorReason_UNSUPPORTED_FORMAT ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "UNSUPPORTED_FORMAT",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":            0,
		"UNSUPPORTED_FORMAT": 1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_oss_v4_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_oss_v4_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_oss_v4_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_oss_v4_error_reason_proto protoreflect.FileDescriptor

const file_oss_v4_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x19oss/v4/error_reason.proto\x12\x10xmux.core.oss.v4\x1a\x13errors/errors.proto*8\n" +
	"\vErrorReason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x16\n" +
	"\x12UNSUPPORTED_FORMAT\x10\x01\x1a\x04\xa0E\xf4\x03B%Z#git.xdea.xyz/XMUS/oss/api/oss/v4;v4b\x06proto3"

var (
	file_oss_v4_error_reason_proto_rawDescOnce sync.Once
	file_oss_v4_error_reason_proto_rawDescData []byte
)

func file_oss_v4_error_reason_proto_rawDescGZIP() []byte {
	file_oss_v4_error_reason_proto_rawDescOnce.Do(func() {
		file_oss_v4_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oss_v4_error_reason_proto_rawDesc), len(file_oss_v4_error_reason_proto_rawDesc)))
	})
	return file_oss_v4_error_reason_proto_rawDescData
}

var file_oss_v4_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oss_v4_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: xmux.core.oss.v4.ErrorReason
}
var file_oss_v4_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oss_v4_error_reason_proto_init() }
func file_oss_v4_error_reason_proto_init() {
	if File_oss_v4_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oss_v4_error_reason_proto_rawDesc), len(file_oss_v4_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oss_v4_error_reason_proto_goTypes,
		DependencyIndexes: file_oss_v4_error_reason_proto_depIdxs,
		EnumInfos:         file_oss_v4_error_reason_proto_enumTypes,
	}.Build()
	File_oss_v4_error_reason_proto = out.File
	file_oss_v4_error_reason_proto_goTypes = nil
	file_oss_v4_error_reason_proto_depIdxs = nil
}
